inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Include:
    - Rakefile
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "public/**/*"
    - "tmp/**/*"